spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:db;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
      username: sa
      minimum-idle: 20
      maximum-pool-size: 100
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always

token:
  secret: TEST
  validity: 86400